# Generated by Django 2.0.7 on 2018-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0006_auto_20181221_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/products/img'),
        ),
    ]
